### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by christinach** [pulibrary/.github#4]
### Introduction

Add Code of Conduct in the repositories.

### Acceptance criteria

- [x] The PR has a code of conduct document.
- [x] Leave the PR open until it receives feedback from all the teams.
- [x] Post the PR in the devs channel.
- [x] Update the contact info to be lsupport.

### Notes

- [contributor-covenant](https://www.contributor-covenant.org/)
- [princeton ansible Code of Conduct](https://github.com/pulibrary/princeton_ansible/blob/main/CODE_OF_CONDUCT.md)

**Comment by kevinreiss** [comment]
I'm all for adding this, but is there a way we can do so in one place as a default the way we did with the issue templates?

**Comment by hackartisan** [comment]
Maybe we could write something into the pul-it-handbook and add a code of conduct file to every other project that contains a link to the centrally-managed file?

**Comment by maxkadel** [comment]
@hackartisan - can you share more about why you prefer that approach?

**Comment by hackartisan** [comment]
Sure! I just thought it would be easier to update it we have the text located in a single location.

**Comment by hackartisan** [comment]
Oh, will it auto-populate from this repo? If so then that works for me!

**Comment by maxkadel** [comment]
@hackartisan  - that's the assumption I'm working on, yes.

**Comment by maxkadel** [comment]
Will be discussed in Manager's meeting June 1.
